"""
Pretrained checkpoint loader.

Handles state_dict naming inconsistencies between training-time code and
this architecture by stripping torch.compile() prefixes and removing
stale RoPE buffer keys (cos_cached/sin_cached) that have shapes incompatible
with this implementation. Missing buffer keys are regenerated by the
architecture; only missing learnable parameters are treated as errors.
"""

import os
import torch

from .vit_architecture import VisionTransformer, PE_TYPES


def detect_architecture(state_dict):
    """Detect patch_size and img_size from checkpoint state_dict."""
    # patch_embed.proj is Conv2d(3, embed_dim, k=patch_size, s=patch_size)
    proj_weight = state_dict.get("patch_embed.proj.weight")
    if proj_weight is None:
        raise ValueError("Cannot detect patch_size: patch_embed.proj.weight missing")
    patch_size = proj_weight.shape[2]  # kernel size

    # Try learned PE shape (1, num_patches+1, embed_dim)
    pe_buffer_names = ["pos_encoding.pos_embed", "pos_encoding.pe"]
    num_patches_plus_1 = None
    for name in pe_buffer_names:
        if name in state_dict:
            num_patches_plus_1 = state_dict[name].shape[1]
            break

    if num_patches_plus_1 is not None:
        num_patches = num_patches_plus_1 - 1
        img_size = int((num_patches ** 0.5) * patch_size)
    else:
        # RoPE/ALiBi don't store PE buffer at top level
        # Infer from training convention: ImageNet-100 uses 224x224, patch 16
        img_size = 224 if patch_size == 16 else 32

    return patch_size, img_size


def load_pretrained_model(checkpoint_root, pe_type, seed,
                          num_classes=100, device="cuda"):
    """
    Load a pretrained ViT-Base checkpoint with PE-aware state_dict handling.
    """
    if pe_type not in PE_TYPES:
        raise ValueError(f"pe_type must be one of {PE_TYPES}, got {pe_type}")

    path = os.path.join(checkpoint_root, f"{pe_type}_seed{seed}", "best_model.pth")
    if not os.path.exists(path):
        print(f"[MISSING] {path}")
        return None

    state = torch.load(path, map_location=device, weights_only=True)
    # Strip torch.compile() prefix if present
    state = {k.replace("_orig_mod.", ""): v for k, v in state.items()}

    patch_size, img_size = detect_architecture(state)

    torch.manual_seed(seed)
    model = VisionTransformer(
        img_size=img_size,
        patch_size=patch_size,
        num_classes=num_classes,
        embed_dim=768,
        depth=12,
        num_heads=12,
        mlp_ratio=4.0,
        dropout=0.1,
        pe_type=pe_type,
    ).to(device)

    # Strip stale RoPE buffer keys (shape mismatch between training and architecture)
    keys_to_delete = [k for k in state.keys()
                       if "rope.cos_cached" in k or "rope.sin_cached" in k]
    for k in keys_to_delete:
        del state[k]

    missing, unexpected = model.load_state_dict(state, strict=False)

    if missing:
        learnable_missing = [k for k in missing
                              if not any(s in k for s in ["inv_freq", "cos_cached", "sin_cached",
                                                            "rel_dist", "slopes", "pe"])]
        if learnable_missing:
            raise RuntimeError(f"Missing learnable parameters: {learnable_missing}")

    model.eval()
    return model


def list_available_checkpoints(checkpoint_root, pe_types=None, seeds=None):
    """List which (pe_type, seed) checkpoints are available on disk."""
    if pe_types is None:
        pe_types = PE_TYPES
    if seeds is None:
        seeds = [42, 123, 456]

    available = []
    for pe in pe_types:
        for s in seeds:
            path = os.path.join(checkpoint_root, f"{pe}_seed{s}", "best_model.pth")
            if os.path.exists(path):
                available.append((pe, s))
    return available
